
// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.
// To update this file, edit the `UpdateFirebaseProjectTool` in the Firebase Studio console.
export const firebaseConfig = {
  "apiKey": "REDACTED",
  "authDomain": "REDACTED",
  "projectId": "REDACTED",
  "storageBucket": "REDACTED",
  "messagingSenderId": "REDACTED",
  "appId": "REDACTED"
};
